external_base_url: "https://${LEIHS_HOSTNAME}"

time_zone: Bern
local_currency_string: CHF

# see <https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration>
mail_delivery_method: smtp
smtp_address: localhost
smtp_port: 25
smtp_domain: ${LEIHS_HOSTNAME}
smtp_username:
smtp_password:
smtp_enable_starttls_auto: f
smtp_openssl_verify_mode: 0

ldap_config:
